### ISSUE TITLE
Config Population - After TV Discovery

### ISSUE THREAD

**Issue by TheEngineerGuy** [mmende/homebridge-samsungtv-control2#1]
This is possibly an enhancement we can do during the polishing up phase. Once TV is discovered and shown in log, USN and Remote port still needs to be manually added to the config.

**Comment by mmende** [comment]
It should actually not be necessary to add the tv's at all to the config. If the plugin finds infos to a tv in the config the values set there are just used to overwrite the discovered values for the tv. However there might need to be some adjustments made for the port being used depending on the model. For now the remote control port defaults to 55000 for tv's older than 2014 and 8002 otherwise. However some models seem to expose the rc at port 8001.

**Comment by mmende** [comment]
I am closing this issue because it is not required at all to add a tv to the config if for example all you need are the remote buttons in the iOS control center remote app. The way it works now is, if you want to configure your tv, copy the usn from the logs into your config and make your changes. It is furthermore not so trivial to rewrite the homebridge config (tried that in earlier versions of 2.0.0-alpha.xx). In the production environment it just wouldn't work anymore. Therefore I think the way it works now is a good compromise between easy setup and customizability.
