### ISSUE TITLE
ENOENT error in homebridge

### ISSUE THREAD

**Issue by MBarti** [mmende/homebridge-samsungtv-control2#10]
Hi,

I've just installed the plugin on my JU6500 series and managed to successfully go throught the first steps - i.e. successfully paired with pair1, the plugin correctly sent "mute".

But:
Once I add the configuration to config.json, homebridge encounters an error.

1. I cannot find the uuid in the logs
2. homebridge stops with ENOENT error

`Jul 26 12:16:34 raspberrypi homebridge[15887]: [7/26/2020, 12:16:34 PM] Homebridge is running on port 51826.
Jul 26 12:16:35 raspberrypi homebridge[15887]: { [Error: ENOENT: no such file or directory, mkdir '/.node-persist'
Jul 26 12:16:35 raspberrypi homebridge[15887]: ]
Jul 26 12:16:35 raspberrypi homebridge[15887]:   errno: -2,
Jul 26 12:16:35 raspberrypi homebridge[15887]:   code: 'ENOENT',
Jul 26 12:16:35 raspberrypi homebridge[15887]:   syscall: 'mkdir',
Jul 26 12:16:35 raspberrypi homebridge[15887]:   path: '/.node-persist' }
Jul 26 12:16:35 raspberrypi homebridge[15887]: { [Error: ENOENT: no such file or directory, mkdir '/.node-persist'
Jul 26 12:16:35 raspberrypi homebridge[15887]: ]
Jul 26 12:16:35 raspberrypi homebridge[15887]:   errno: -2,
Jul 26 12:16:35 raspberrypi homebridge[15887]:   code: 'ENOENT',
Jul 26 12:16:35 raspberrypi homebridge[15887]:   syscall: 'mkdir',
Jul 26 12:16:35 raspberrypi homebridge[15887]:   path: '/.node-persist' }
Jul 26 12:16:35 raspberrypi homebridge[15887]: [7/26/2020, 12:16:35 PM] [Amplifier] poll end, state: true
Jul 26 12:16:35 raspberrypi homebridge[15887]: [7/26/2020, 12:16:35 PM] Got SIGTERM, shutting down Homebridge...`

Here's my config:
{
            "devices": [
                {
                    "name": "Samsung TV",
                    "usn": "uuid:b0f374b8-baac-4839-a78d-1234567890123",
                    "token": "[deleted for privacy]=="
                }
            ],
            "platform": "SamsungTVControl"
        }

(I found the uuid in the tv's web console at IP:8001/ms/1.0/ , hope it's the right one; regardless, even without putting it in the config, homebridge dies)

**Comment by mmende** [comment]
Hi,

Nice to hear you made it half way through. 
At the moment it is necessary that the plugin discovers the device itself before the device will show up as external accessory because it fetches some additional device infos and uses upnp also to keep track of possibly changing ip addresses and upnp location. However, the error might lead to crashing homebridge before the device discovery even starts. The problem seems to be caused by node-persist trying to create the persistent directory at `/.node-persist`. You might just try to create the directory yourself and change the permissions of that folder generously for testing like `mkdir /.node-persist` and `chmod 777 /.node-persist`. I hope this leads to homebridge not crashing anymore and showing your tv correctly with the usn (remember to turn your tv on before restarting homebridge).

PS: If you know the user homebridge is running under, it would be better to make this user the owner of this directory
chown homebridge:homebridge .node-persist (if the user is homebridge e.g.) instead of making the directory read/writable by every user what the previous command does

PS2: I might add an option to add tv's that can for some reason not be discovered over upnp even though this would require setting up a static ip for the tv and finding out some values yourself.

**Comment by mmende** [comment]
I will also change the default location, node-persist is using to the homebridge storage path in the next release... this hopefully solves the problem once and for all.

**Comment by ggroel** [comment]
👍

Gastón

**Comment by ggroel** [comment]
Martin , you still think that the plugin can work for my TV (2010)... ? Jeje

Gastón

**Comment by ggroel** [comment]
Martin,
Trying various things I have found some stuff that maybe can help you (or help me jejejej). With the Samsung_tv plugin (https://github.com/danimal4326/homebridge-samsung_tv#readme) I was able to configure my 2010 samsung to see the status (on / off), I can't actually turn it on or off, but I can see the status at least. On the other hand, with the homebridge-upnp plugin (https://github.com/langovoi/homebridge-upnp#readme) I was able to recognize my TV and it adds a lightbulb to control the volume (and it works !!!). The interesting thing about this last plugin is that it discovers all upnp devices and found that the USN of my Samsung TV is "uuid:f7b6d1b3-847a-3459-3e1e-f8a03ff7bc32::urn:schemas-upnp-org:device:MediaRenderer:1” and it worked when I entered it complete and not just the uuid part.
I mean, thanks to these two plugins I can see the status of my TV and control the volume. Is there any chance that you “blend" these two things on one platform (at least for Samsung <2014)? THANK YOU THANK YOU THANK YOU!!!
On the other hand, I tell you that for 2 or 3 versions of your plugin, the log shows me that the platform is initialized, but it does not find any device, but in previous versions it indicated that 1 device had been found (it did not work later , but at least he informed me that he had found something ... not now). Thank you!!

Gastón

**Comment by mmende** [comment]
Thanks @ggroel ... That actually helps and I have an idea now why your TV (and some others) are not being detected by the device discovery now. I post some more details tomorrow.

**Comment by MBarti** [comment]
@mmende Martin, great tips! Now it works fine. The TV is detected properly and I've added it to homebridge without problems. Now I can finally use it in automations! Thank you!

Ps. For other users: The H/J-series TVs (and maybe others) allow one to turn the TV off, but not on (not even wake-on-lan). So to turn it on in automations I use the Apple TV (via CEC).

**Comment by mmende** [comment]
Awesome... nice to hear that.
