### ISSUE TITLE
Installation fails when trying to install on homebridge

### ISSUE THREAD

**Issue by brj5** [mmende/homebridge-samsungtv-control2#11]
an error is given and I am unable to install the plugin here is the error undefined ls-remote -h -t https://github.com/mmende/samsung-remo
te-models-2014-and-newer.git**** then it says this a couple lines lower: This is related to npm not being able to find a file.

**Comment by mmende** [comment]
This happens sometimes because one of the dependencies is being installed directly from github because it is not published yet (see #9). The problem will be resolved with the next version that I will probably publish in the next few days. I will close this issue for now since it is the same as #9. If for some reason it should still appear with the next version, feel free to reopen the issue.
